version: "3.8"

services:
  openlane-fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: openlane-fastapi
    ports:
      - "5000:5000"  # Expose FastAPI on port 5000
    volumes:
      - .:/app  # Mount the current directory into the container (optional for development)
    networks:
      - openlane-network

networks:
  openlane-network:
    driver: bridge
